use crate::control::{actions::{r#move::Move, rotate_arm::RotateArm}, landmark::Landmark, sequences::Sequence, states::yaw_servo::ArmPosition};

pub fn main_sequence() -> Sequence {
    Sequence::new()
        .then(RotateArm::to(ArmPosition::Middle))
        .then(Move::to(Landmark::QrZone))
        .then(Move::to(Landmark::SourceZone))
        .then(RotateArm::to(ArmPosition::Right))
        .then(RotateArm::to(ArmPosition::Middle))
        .then(Move::to(Landmark::CentralRightCrossing))
        .then(Move::to(Landmark::TemporaryStorageZone))
        .then(RotateArm::to(ArmPosition::Left))
        .then(RotateArm::to(ArmPosition::Middle))
        .then(Move::to(Landmark::UpperLeftTurn))
        .then(Move::to(Landmark::FinalProcessingZone))
        .then(RotateArm::to(ArmPosition::Right))
        .then(RotateArm::to(ArmPosition::Middle))
        .then(Move::to(Landmark::UpperRightTurn))
        .then(Move::to(Landmark::SourceZone))
        .then(RotateArm::to(ArmPosition::Right))
        .then(RotateArm::to(ArmPosition::Middle))
        .then(Move::to(Landmark::CentralRightCrossing))
        .then(Move::to(Landmark::TemporaryStorageZone))
        .then(RotateArm::to(ArmPosition::Left))
        .then(RotateArm::to(ArmPosition::Middle))
        .then(Move::to(Landmark::UpperLeftTurn))
        .then(Move::to(Landmark::FinalProcessingZone))
        .then(RotateArm::to(ArmPosition::Right))
        .then(RotateArm::to(ArmPosition::Middle))
        .then(Move::to(Landmark::UpperRightTurn))
        .then(Move::to(Landmark::Start))
}